
package one.microstream.microstreamdemo.ui;

import com.vaadin.flow.component.button.Button;
import com.vaadin.flow.component.grid.Grid;
import com.vaadin.flow.component.orderedlayout.HorizontalLayout;
import com.vaadin.flow.component.orderedlayout.VerticalLayout;


public class MyTestWindow extends VerticalLayout
{

	/**
	 *
	 */
	public MyTestWindow()
	{
		super();
		this.initUI();
	}

	/* WARNING: Do NOT edit!<br>The content of this method is always regenerated by the UI designer. */
	// <generated-code name="initUI">
	private void initUI()
	{
		this.horizontalLayout = new HorizontalLayout();
		this.button           = new Button();
		this.grid             = new Grid<>();
		this.button2          = new Button();

		this.button.setText("Button");
		this.grid.setMaxHeight("300");
		this.grid.setSelectionMode(Grid.SelectionMode.SINGLE);
		this.button2.setText("Button");

		this.button.setSizeUndefined();
		this.horizontalLayout.add(this.button);
		this.horizontalLayout.setWidthFull();
		this.horizontalLayout.setHeight(null);
		this.grid.setWidthFull();
		this.grid.setHeight("300px");
		this.button2.setSizeUndefined();
		this.add(this.horizontalLayout, this.grid, this.button2);
		this.setSizeFull();
	} // </generated-code>

	// <generated-code name="variables">
	private Button           button, button2;
	private HorizontalLayout horizontalLayout;
	private Grid<?>          grid;
	// </generated-code>
	
}
